PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZAFL_CONFIG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZAFL_CONFIG-FNAME .
    FIELD ZAFL_CONFIG-ENABLED .
    FIELD ZAFL_CONFIG-EXPORT .
    FIELD ZAFL_CONFIG-IMPORT .
    FIELD ZAFL_CONFIG-TABLE_IN .
    FIELD ZAFL_CONFIG-TABLE_OUT .
    FIELD ZAFL_CONFIG-CHANGE .
    FIELD ZAFL_CONFIG-NO_COMMIT .
    FIELD ZAFL_CONFIG-NO_AUTH_CHECK .
    FIELD ZAFL_CONFIG-CUST_NAME1 .
    FIELD ZAFL_CONFIG-CUST_NAME2 .
    FIELD ZAFL_CONFIG-CUST_NAME3 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZAFL_CONFIG-FNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
